[project]
name = "coc"
requirements = []
costs_version = 1
[contracts.coc]
path = "contracts/coc.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]

[contracts.semi-fungible-token]
path = "contracts/semi-fungible-token.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]

[contracts.sipxxx-semi-fungible-token-trait]
path = "contracts/sipxxx-semi-fungible-token-trait.clar"
depends_on = []

[contracts.wrapped-sip010-sft]
path = "contracts/wrapped-sip010-sft.clar"
depends_on = ["sipxxx-semi-fungible-token-trait"]
